id = "mcp-server-basic-memory"
name = "Basic Memory MCP Server"
description = "Model Context Protocol Server for building persistent knowledge with Basic Memory"
version = "0.0.1"
schema_version = 1
authors = ["Ossfellow <ossfellow@users.noreply.github.com>"]
repository = "https://github.com/ossfellow/zed-mcp-server-basic-memory"

[context_servers.mcp-server-basic-memory]
name = "Basic Memory MCP Server"
